package support

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"

	"github.com/7samael7/Piper/engine/internal/pipeline/model"
)

func RenderProviderSupport(registry *Registry) []byte {
	var output bytes.Buffer
	output.WriteString("# Provider Support Reference\n\n")
	output.WriteString("<!-- Generated by `cd engine && go run ./cmd/supportdoc -write`. Do not edit by hand. -->\n\n")
	output.WriteString("Piper is a deterministic local approximation. Hosted CI remains the final source of truth.\n\n")
	output.WriteString("Statuses: `supported-local`, `emulated`, `partial`, `validation-only`, `unsupported`, and `requires-consent`.\n\n")
	output.WriteString("Runtime dispositions: `execute`, `emulate`, `inspect-only`, `reject`, and `consent`.\n\n")
	fmt.Fprintf(&output, "This document is generated from %d registry records. Each row includes the parser contract, runtime behavior, hosted difference, security note, fallback, and related test evidence.\n\n", len(registry.Features))

	providers := []model.ProviderID{model.ProviderCommon, model.ProviderGitHub, model.ProviderGitLab, model.ProviderAzure}
	headings := map[model.ProviderID]string{
		model.ProviderCommon: "Common behavior", model.ProviderGitHub: "GitHub Actions",
		model.ProviderGitLab: "GitLab CI/CD", model.ProviderAzure: "Azure Pipelines",
	}
	for _, provider := range providers {
		output.WriteString("## " + headings[provider] + "\n\n")
		entries := []Entry{}
		for _, entry := range registry.Features {
			if entry.Provider == provider {
				entries = append(entries, entry)
			}
		}
		sort.Slice(entries, func(i, j int) bool {
			if entries[i].Category != entries[j].Category {
				return entries[i].Category < entries[j].Category
			}
			return entries[i].ID < entries[j].ID
		})
		output.WriteString("| Category / feature | Status / runtime | Parser contract | Local behavior | Hosted difference | Security / fallback / tests |\n")
		output.WriteString("| --- | --- | --- | --- | --- | --- |\n")
		for _, entry := range entries {
			fmt.Fprintf(&output, "| <a id=\"%s\"></a>%s — %s (`%s`) | `%s` / `%s` | %s | %s | %s | %s Fallback: %s Tests: %s |\n",
				entry.Documentation, titleCase(entry.Category), escapeCell(entry.Title), entry.ID,
				entry.Status, entry.RuntimeDisposition, escapeCell(entry.ParserSupport), escapeCell(entry.LocalBehavior),
				escapeCell(entry.HostedDifferences), escapeCell(entry.SecurityImplications), escapeCell(entry.Fallback),
				testLinks(entry.RelatedTests))
		}
		output.WriteString("\n")
	}
	return bytes.TrimSuffix(output.Bytes(), []byte("\n"))
}

func ProviderSupportMatches(existing []byte, registry *Registry) bool {
	return bytes.Equal(normalizeLineEndings(existing), RenderProviderSupport(registry))
}

func ContractDigest(registry *Registry) string {
	var canonical bytes.Buffer
	for _, entry := range registry.Features {
		fmt.Fprintf(&canonical, "%s\t%s\t%s\n", entry.ID, entry.Status, entry.RuntimeDisposition)
	}
	sum := sha256.Sum256(canonical.Bytes())
	return hex.EncodeToString(sum[:])
}

func normalizeLineEndings(value []byte) []byte {
	return bytes.ReplaceAll(value, []byte("\r\n"), []byte("\n"))
}

func titleCase(value string) string {
	words := strings.FieldsFunc(value, func(r rune) bool { return r == '-' || r == '_' || r == ' ' })
	for index, word := range words {
		if word != "" {
			words[index] = strings.ToUpper(word[:1]) + word[1:]
		}
	}
	return strings.Join(words, " ")
}

func escapeCell(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	value = strings.ReplaceAll(value, "\n", " ")
	return value
}

func testLinks(paths []string) string {
	links := make([]string, 0, len(paths))
	for _, path := range paths {
		links = append(links, fmt.Sprintf("[%s](../%s)", escapeCell(path), path))
	}
	return strings.Join(links, ", ")
}
