package support

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"
	"strings"

	"github.com/7samael7/Piper/engine/internal/pipeline/model"
)

func RenderProviderSupport(registry *Registry) []byte {
	var output bytes.Buffer
	output.WriteString("# Provider Support Reference\n\n")
	output.WriteString("<!-- Generated by `cd engine && go run ./cmd/supportdoc -write`. Do not edit by hand. -->\n\n")
	output.WriteString("Piper is a deterministic local approximation. Hosted CI remains the final source of truth.\n\n")
	output.WriteString("Statuses: `supported-local`, `emulated`, `partial`, `validation-only`, `unsupported`, and `requires-consent`.\n\n")
	output.WriteString("Runtime dispositions: `execute`, `emulate`, `inspect-only`, `reject`, and `consent`.\n\n")

	providers := []model.ProviderID{model.ProviderCommon, model.ProviderGitHub, model.ProviderGitLab, model.ProviderAzure}
	headings := map[model.ProviderID]string{
		model.ProviderCommon: "Common behavior", model.ProviderGitHub: "GitHub Actions",
		model.ProviderGitLab: "GitLab CI/CD", model.ProviderAzure: "Azure Pipelines",
	}
	for _, provider := range providers {
		output.WriteString("## " + headings[provider] + "\n\n")
		entries := []Entry{}
		for _, entry := range registry.Features {
			if entry.Provider == provider {
				entries = append(entries, entry)
			}
		}
		sort.Slice(entries, func(i, j int) bool {
			if entries[i].Category != entries[j].Category {
				return entries[i].Category < entries[j].Category
			}
			return entries[i].ID < entries[j].ID
		})
		output.WriteString("| Category / feature | Status | Runtime | Local behavior | Hosted difference / fallback |\n")
		output.WriteString("| --- | --- | --- | --- | --- |\n")
		for _, entry := range entries {
			fmt.Fprintf(&output, "| <a id=\"%s\"></a>%s — %s (`%s`) | `%s` | `%s` | %s | %s Fallback: %s |\n",
				entry.Documentation, titleCase(entry.Category), escapeCell(entry.Title), entry.ID,
				entry.Status, entry.RuntimeDisposition, escapeCell(entry.LocalBehavior),
				escapeCell(entry.HostedDifferences), escapeCell(entry.Fallback))
		}
		output.WriteString("\n")
	}
	return bytes.TrimSuffix(output.Bytes(), []byte("\n"))
}

func ContractDigest(registry *Registry) string {
	var canonical bytes.Buffer
	for _, entry := range registry.Features {
		fmt.Fprintf(&canonical, "%s\t%s\t%s\n", entry.ID, entry.Status, entry.RuntimeDisposition)
	}
	sum := sha256.Sum256(canonical.Bytes())
	return hex.EncodeToString(sum[:])
}

func titleCase(value string) string {
	words := strings.FieldsFunc(value, func(r rune) bool { return r == '-' || r == '_' || r == ' ' })
	for index, word := range words {
		if word != "" {
			words[index] = strings.ToUpper(word[:1]) + word[1:]
		}
	}
	return strings.Join(words, " ")
}

func escapeCell(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	value = strings.ReplaceAll(value, "\n", " ")
	return value
}
